Ext.define('App.view.project.ShowDetails', {
    extend: 'Ext.Panel',
    xtype: 'projectshowdetails',

    title: 'Détails',

    bind: {
        record: '{record}'
    },

    tpl: [
        '<div class="block-section">',
        '<div class="item">',
                '<div class="label">Référence</div>',
                '<div class="value">{reference}</div>',
            '</div>',
            '<div class="item">',
                '<div class="label">Code Projet</div>',
                '<div class="value">{id}</div>',
            '</div>', 
            
            '<div class="item">',
                '<div class="label">Programme</div>',
                '<div class="value">{programme}</div>',
            '</div>',

            '<div class="item">',
                '<div class="label">Rubrique</div>',
                '<div class="value">{rubrique}</div>',
            '</div>',

            '<div class="item">',
                '<div class="label">Exercice</div>',
                '<div class="value">{annee}</div>',
            '</div>',
        '</div>',

        '<div class="block-section">',
            '<div class="item">',
                '<div class="label">Type</div>',
                '<div class="value">',
                    '<tpl if="est_projet">',
                        '<span>Projet </span>',
                    '</tpl>',
                    '<tpl if="est_AGR">',
                        '<span>AGR </span>',
                    '</tpl>',
                    '<tpl if="est_infrastructure">',
                        '<span>Infrastructure </span>',
                    '</tpl>',
                    '<tpl if="est_PCD">',
                        '<span>PCD </span>',
                    '</tpl>',
                    '<tpl if="est_EPS">',
                        '<span>EPS </span>',
                    '</tpl>',
                '</div>',
                '<div class="extra">{type}</div>',
            '</div>',
            
            '<div class="item">',
                '<div class="label">Secteur d\'activité</div>',
                '<div class="value">{secteur_activite_principal}</div>',
                '<div class="extra">{secteur_activite}</div>',
            '</div>',

            '<div class="item">',
                '<div class="label">Bénéficiaires prévus / Capacitié</div>',
                '<div class="value">',
                    '{pop_benef_total_prevu} / {capacite_accueil}',
                    '<div class="item-info">',
                        '<span class="x-fa fa-female"></span> {pop_benef_femme_prevu} &nbsp;&nbsp;&nbsp;<span class="x-fa fa-male"></span> {pop_benef_homme_prevu} &nbsp;&nbsp;&nbsp;',
                        '<span class="x-fa fa-child"></span> {pop_benef_jeune_prevu} &nbsp;&nbsp;&nbsp;<span class="x-fa fa-home"></span> {pop_benef_menage_prevu}',
                    '</div>',
                '</div>',
            '</div>',   

			'<div class="item">',
                '<div class="label">Bénéficiaires réels</div>',
                '<div class="value">',
                    '{pop_benef_total_reel}',
                    '<div class="item-info">',
                        '<span class="x-fa fa-female"></span> {pop_benef_femme_reel} &nbsp;&nbsp;&nbsp;<span class="x-fa fa-male"></span> {pop_benef_homme_reel} &nbsp;&nbsp;&nbsp;',
                        '<span class="x-fa fa-child"></span> {pop_benef_jeune_reel} &nbsp;&nbsp;&nbsp;<span class="x-fa fa-home"></span> {pop_benef_menage_reel}',
                    '</div>',
                '</div>',
                '</div>',
            '</div>',     
			
        '</div>',

        '<div class="block-section">',
            '<div class="item">',
                '<div class="label">Statut</div>',
                '<div class="value">{statut}</div>',
                '<div class="extra">{etat_physique_actuel}  ( {tx_avancement_physique} % )</div>',
                '<div class="extra">{motif_souffrance}</div>',
            '</div>',            
        '</div>',

        '<div class="block-section full-width">',
            '<div class="item">',
                '<div class="label">Consistance</div>',
                '<div class="value">{consistance}</div>',
            '</div>',

            '<div class="item">',
                '<div class="label">Objectifs</div>',
                '<div class="value">{objectifs}</div>',
            '</div>',

            '<div class="item">',
                '<div class="label">Maitre d\'ouvrage</div>',
                '<div class="value">{MOA}</div>',
                '<div class="extra">{MOA_delegue}</div>',
            '</div>',


            '<div class="item">',
                '<div class="label">Délai d\'exécution prévu</div>',
                '<div class="value">{duree_projet}</div>',
            '</div>',

            '<div class="item">',
                '<div class="label">Convention</div>',
                '<div class="value">',
                    '<a class="item-title" href="/uploads/{convention}">{convention}</a>',
                '</div>',
            '</div>',
        '</div>'
    ]
});