Ext.define('App.store.INDH.Quartiers', {
    extend: 'Ext.data.Store',

    alias: 'store.quartiers',

    fields: ['value', 'commune'],

    data: [
        { value: "DIVERS DOUARS DE LA COMMUNE", commune: "" },
        { value: "ACHKIR", commune: "" },
        { value: "AGDAL", commune: "" },
        { value: "AGDAL-KASBAH", commune: "" },
        { value: "AIN AGOUAL", commune: "" },
        { value: "AIN AKRA", commune: "" },
        { value: "AIN AL KATE", commune: "" },
        { value: "AIN CHOUBIK", commune: "" },
        { value: "AÏN JEMAA CENTRE", commune: "" },
        { value: "AIN KARMA CENTRE", commune: "" },
        { value: "AIN KHAROUBA", commune: "" },
        { value: "AIN ORMA CENTRE", commune: "" },
        { value: "AIN RJAL", commune: "" },
        { value: "AÏT ABBA", commune: "" },
        { value: "AÏT ABDI", commune: "" },
        { value: "AIT ALI OMOUSSA", commune: "" },
        { value: "AIT ALI OU MOUSSA", commune: "" },
        { value: "AIT BEN BOUAZA", commune: "" },
        { value: "AIT BEN BOUAZA|AIT BOUYAHYA", commune: "" },
        { value: "AIT FETTOU", commune: "" },
        { value: "AIT H'SSAIN", commune: "" },
        { value: "AIT HSSAINE", commune: "" },
        { value: "AIT HSSAINE|DCHAR EL KHALI", commune: "" },
        { value: "AIT HSSAINE|SIDI ABDELLAH BEN TAAZIZT|HAFRAT BEN TAYEB", commune: "" },
        { value: "AIT ISHAK", commune: "" },
        { value: "AIT ISHAQ", commune: "" },
        { value: "AIT LACHOUR", commune: "" },
        { value: "AIT LAHCEN", commune: "" },
        { value: "AIT MOUSSA OU HAMI", commune: "" },
        { value: "AIT OTMANE IHMARINE", commune: "" },
        { value: "AIT OUALD MAHDOUNA AIN CHKAF", commune: "" },
        { value: "AIT OUALLAL CENTRE", commune: "" },
        { value: "AIT TALEB ALI", commune: "" },
        { value: "AIT TOURGINE", commune: "" },
        { value: "AL AMAL-RIAD", commune: "" },
        { value: "AL ANSAR", commune: "" },
        { value: "AL BASSATINE", commune: "" },
        { value: "AL INARA", commune: "" },
        { value: "AL IZDIHAR-ESSALAM", commune: "" },
        { value: "AL KHOLT", commune: "" },
        { value: "AL MAKHATIR - ZOUALET", commune: "" },
        { value: "AL MANSOUR", commune: "" },
        { value: "AMAL EL MENEH", commune: "" },
        { value: "ANCIENNE MEDINA", commune: "" },
        { value: "ANNASR", commune: "" },
        { value: "AOUINTE RMEL", commune: "" },
        { value: "ARAB SABAH AL GAADA", commune: "" },
        { value: "ARIB LAMRANI", commune: "" },
        { value: "ASSADA", commune: "" },
        { value: "ATAHRIR", commune: "" },
        { value: "ATAKADOUM", commune: "" },
        { value: "AZIB EL HAMRA", commune: "" },
        { value: "AZIB EL HAMRA|OULED DAOUIA", commune: "" },
        { value: "AZIB SKALI", commune: "" },
        { value: "AZOHOUR", commune: "" },
        { value: "BAB BELKARI", commune: "" },
        { value: "BAB BELKARI CHRICHIRA", commune: "" },
        { value: "BAB BERDAINE", commune: "" },
        { value: "BAB BERDAINE|CARRIERE SAYED MOUSSA|TOUARGA", commune: "" },
        { value: "BAB BOUAAMAYER", commune: "" },
        { value: "BAB JDID", commune: "" },
        { value: "BAB LAHJAR", commune: "" },
        { value: "BAICHE AL KHOLAWA", commune: "" },
        { value: "BARAMILA", commune: "" },
        { value: "BARAMILA|SIDI AMEUR|AIN CHOUBIK|AL INARA", commune: "" },
        { value: "BENI AMMAR", commune: "" },
        { value: "BENI CHAGDAL|HAJ JILLALI", commune: "" },
        { value: "BENI JANADE", commune: "" },
        { value: "BENI MANSOUR", commune: "" },
        { value: "BENI MERAZ", commune: "" },
        { value: "BENI MHAMED", commune: "" },
        { value: "BENI WARRADE", commune: "" },
        { value: "BIR SOLTANE", commune: "" },
        { value: "BIRIMA", commune: "" },
        { value: "BNI MERAAS", commune: "" },
        { value: "BNIMHAMED", commune: "" },
        { value: "BORJ MACHKOUK", commune: "" },
        { value: "BORJ MOULAY OMAR", commune: "" },
        { value: "BORJ MY OMAR", commune: "" },
        { value: "BOUALKA", commune: "" },
        { value: "BOUAMAYER", commune: "" },
        { value: "BOUÂNANE", commune: "" },
        { value: "BOUASSEL", commune: "" },
        { value: "BOUASSEL|BNI MERAAS", commune: "" },
        { value: "BOUFEKRANE CENTRE", commune: "" },
        { value: "BOUMANDARA", commune: "" },
        { value: "BOUMERRAK", commune: "" },
        { value: "BRIDIA", commune: "" },
        { value: "CARRIÈRE KM10", commune: "" },
        { value: "CARRIERE SAIDIA", commune: "" },
        { value: "CARRIERE SAIDIA-N'ZALAT", commune: "" },
        { value: "CARRIERE SAIDIA-N-ZALAT", commune: "" },
        { value: "CENTRE AGRICOL", commune: "" },
        { value: "CENTRE AGRICOLE", commune: "" },
        { value: "CHARQUAOUA", commune: "" },
        { value: "CHATOUANE", commune: "" },
        { value: "CHRAIF", commune: "" },
        { value: "COOPÉRATIVE AHMED LAMSAREJ", commune: "" },
        { value: "COOPÉRATIVE AL FATH", commune: "" },
        { value: "COOPERATIVE AL KHAIR", commune: "" },
        { value: "COOPÉRATIVE AL WIDAD", commune: "" },
        { value: "COOPÉRATIVE EL MASSIRA", commune: "" },
        { value: "COOPÉRATIVE KAFS", commune: "" },
        { value: "COOPÉRATIVE OUED EDDAHAB", commune: "" },
        { value: "COOPÉRATIVE SAKIA EL HAMRA", commune: "" },
        { value: "CT AGRICOLE", commune: "" },
        { value: "DAR BEN ABDELLAH", commune: "" },
        { value: "DAR OUM SOLTAN", commune: "" },
        { value: "DHAR EL KHOLF", commune: "" },
        { value: "DHAR EL KHOLF|DANDOUNA, SIDI MOUSSA", commune: "" },
        { value: "D'HAR N'SSOUR", commune: "" },
        { value: "DKHISSA", commune: "" },
        { value: "DKHISSA|M'GHASSIYINE|OUALILI|SIDI ABDELLAH EL KHAYAT|N'ZALA BENI AMMAR", commune: "" },
        { value: "DOUAR AIN KARMA", commune: "" },
        { value: "DOUAR AGBANE", commune: "" },
        { value: "DOUAR AICHA RAHOU", commune: "" },
        { value: "DOUAR AICHA RAHOU|N'ZALA BENI AMMAR|BENI AMMAR", commune: "" },
        { value: "DOUAR AIN AKRA", commune: "" },
        { value: "DOUAR AIT ALI", commune: "" },
        { value: "DOUAR AIT ALI BALKOUM", commune: "" },
        { value: "DOUAR AIT LEMSSIR", commune: "" },
        { value: "DOUAR AIT LGHAZI AIT DRISS OUASSOU", commune: "" },
        { value: "DOUAR AIT MISSOUR", commune: "" },
        { value: "DOUAR AIT YAKOUB", commune: "" },
        { value: "DOUAR AL KIFANE NOUAJI", commune: "" },
        { value: "DOUAR BHALIL", commune: "" },
        { value: "DOUAR BNI MGUILD EL GHARBIA (RR)", commune: "" },
        { value: "DOUAR CHAABANAT", commune: "" },
        { value: "DOUAR CHAABANAT|DAYYAT ABBOU", commune: "" },
        { value: "DOUAR CHOUAKER", commune: "" },
        { value: "DOUAR DOUM", commune: "" },
        { value: "DOUAR HAJA EL GHARBIA (AIN ORMA)", commune: "" },
        { value: "DOUAR JBALA", commune: "" },
        { value: "DOUAR JDID", commune: "" },
        { value: "DOUAR LAACHACH", commune: "" },
        { value: "DOUAR M'GHASSIYNE", commune: "" },
        { value: "DOUAR OULED HANOUNE JAAOUNA", commune: "" },
        { value: "DOUAR OUTITA", commune: "" },
        { value: "DOUAR SIDI CHBANI", commune: "" },
        { value: "DOUIMNIE", commune: "" },
        { value: "DOUKARA", commune: "" },
        { value: "DOUAR SIDI BOUKHABZA", commune: "" },
        { value: "DRIOUAT", commune: "" },
        { value: "DRIOUAT|SIDI MJAHED", commune: "" },
        { value: "EL BASSATINE", commune: "" },
        { value: "EL GANDOUL", commune: "" },
        { value: "EL HOUCINE GUEROUANI", commune: "" },
        { value: "EL HOUFRA", commune: "" },
        { value: "EL KALAA", commune: "" },
        { value: "EL KHOLT", commune: "" },
        { value: "EL KIFANE", commune: "" },
        { value: "EL MASSAKINE", commune: "" },
        { value: "ENA", commune: "" },
        { value: "ENNAIM", commune: "" },
        { value: "ENNASR", commune: "" },
        { value: "FERTASSA", commune: "" },
        { value: "GHOMRA", commune: "" },
        { value: "HACIENDA", commune: "" },
        { value: "HAFRAT BEN TAYEB", commune: "" },
        { value: "HAJ KADDOUR CENTRE", commune: "" },
        { value: "HAJ KADDOUR CENTRE|AIN AKRA OUED EDDAHAB", commune: "" },
        { value: "HAMRAOUA", commune: "" },
        { value: "HARCHA", commune: "" },
        { value: "HAY AL QODS", commune: "" },
        { value: "HAY EL KHYAM", commune: "" },
        { value: "HAY LOKTANE AL INBIAAT CR N'ZALAT BNI AMMAR", commune: "" },
        { value: "HAY SALAM", commune: "" },
        { value: "H'DACHIYINE", commune: "" },
        { value: "JAADNA", commune: "" },
        { value: "JAJOUIYINE (EX. KAFE HMARA)", commune: "" },
        { value: "JDID", commune: "" },
        { value: "JNANE BEN HLIMA", commune: "" },
        { value: "KARIAT BNI AMAR", commune: "" },
        { value: "KASBAT HARTANE", commune: "" },
        { value: "KDADRA", commune: "" },
        { value: "KERMET", commune: "" },
        { value: "KHARROUBA", commune: "" },
        { value: "KHAYBER", commune: "" },
        { value: "KORTOBA", commune: "" },
        { value: "LAAMMA", commune: "" },
        { value: "LAAOUIJA", commune: "" },
        { value: "LAAOUIJA|AIN CHOUBIK|BIRIMA|SIDI BABA", commune: "" },
        { value: "LAGHROUSS", commune: "" },
        { value: "LAHBILIYINE", commune: "" },
        { value: "LAHBOUL", commune: "" },
        { value: "LAHFARI", commune: "" },
        { value: "LAKAR", commune: "" },
        { value: "LAKHNADEQ", commune: "" },
        { value: "LAKLIAA", commune: "" },
        { value: "LAKOUAR", commune: "" },
        { value: "LALLA AOUDA", commune: "" },
        { value: "MACHKHA", commune: "" },
        { value: "MACHRA", commune: "" },
        { value: "MACHRAA LAAMOUR", commune: "" },
        { value: "MAHATAT AL KETAR", commune: "" },
        { value: "MAJJAT CENTRE", commune: "" },
        { value: "MAJJAT CENTRE|CARRIÈRE KM10|BRIDIA", commune: "" },
        { value: "MARJANE", commune: "" },
        { value: "MARJANE I", commune: "" },
        { value: "MARJANE II", commune: "" },
        { value: "MECHOUAR", commune: "" },
        { value: "MECHRAA MEKNES", commune: "" },
        { value: "MEKNES", commune: "" },
        { value: "MEKNÈS", commune: "" },
        { value: "MELOUANE", commune: "" },
        { value: "M'GHASSIYINE", commune: "" },
        { value: "M'GHASSIYINE|MOUSSAOUA", commune: "" },
        { value: "M'HAYA CENTRE", commune: "" },
        { value: "M'HAYA CENTRE|HAJ KADDOUR CENTRE|AIN ORMA CENTRE|AÏN JEMAA CENTRE", commune: "" },
        { value: "MIASSA", commune: "" },
        { value: "M'KHATIR", commune: "" },
        { value: "MNASRA", commune: "" },
        { value: "MOUSSAOUA", commune: "" },
        { value: "MOUSSAOUA|DOUAR M'GHASSIYNE", commune: "" },
        { value: "MSAMDA", commune: "" },
        { value: "M'SAMDA|JAADNA", commune: "" },
        { value: "MY ALI", commune: "" },
        { value: "MY BOUAZZA", commune: "" },
        { value: "MY IDRISS ZERHOUNE", commune: "" },
        { value: "N'ZALA BENI AMMAR", commune: "" },
        { value: "OTHMANE IBN AFFANE", commune: "" },
        { value: "OUALILI", commune: "" },
        { value: "OUARZIGHA", commune: "" },
        { value: "OUARZIRA(DKHISSA)", commune: "" },
        { value: "OUED EL MEYAT", commune: "" },
        { value: "OUED FRA", commune: "" },
        { value: "OUED JDIDA CENTRE", commune: "" },
        { value: "OUED JDIDA LA GARE", commune: "" },
        { value: "OUED ROMMANE CENTRE", commune: "" },
        { value: "OUISLANE", commune: "" },
        { value: "OUJAH AROUSS", commune: "" },
        { value: "OUJAH AROUSS|CARRIERE SAIDIA", commune: "" },
        { value: "OULAD MIMOUNE", commune: "" },
        { value: "OULAD N CIR", commune: "" },
        { value: "OULED ABDESSLAM", commune: "" },
        { value: "OULED ALILOU M'HAMED", commune: "" },
        { value: "OULED BENSIDHOUM", commune: "" },
        { value: "OULED EL KADI", commune: "" },
        { value: "OULED N'CIR", commune: "" },
        { value: "OULED RAHMOUNE", commune: "" },
        { value: "OULED SLIM", commune: "" },
        { value: "OULED SLIM|HAY EL KHYAM", commune: "" },
        { value: "OULED SLIM|LAKHRARIB|LHORMIYINE|OULED BRASE", commune: "" },
        { value: "OULED YOUSSEF", commune: "" },
        { value: "OULED ZBIDATE", commune: "" },
        { value: "OULED ZIYANE", commune: "" },
        { value: "OULJA", commune: "" },
        { value: "OURZIGHA|OULAD N CIR", commune: "" },
        { value: "QUARTIER ADMINISTRATIF", commune: "" },
        { value: "RHABAT CHABAB", commune: "" },
        { value: "RHABAT LHARCHA", commune: "" },
        { value: "RIAD", commune: "" },
        { value: "RIAD EL KESTANI", commune: "" },
        { value: "RMIKA", commune: "" },
        { value: "R'MIKA", commune: "" },
        { value: "ROUTE AGOURAI", commune: "" },
        { value: "ROUTE HAJ KADDOUR", commune: "" },
        { value: "SBATA", commune: "" },
        { value: "SIDI ABDELLAH BEN TAAZIZT", commune: "" },
        { value: "SIDI ABDELLAH EL KHAYAT", commune: "" },
        { value: "SIDI ALI", commune: "" },
        { value: "SIDI ALI BEN HAMDOUCH", commune: "" },
        { value: "SIDI AMER", commune: "" },
        { value: "SIDI AMEUR", commune: "" },
        { value: "SIDI AYADE", commune: "" },
        { value: "SIDI BABA", commune: "" },
        { value: "SIDI BABA", commune: "" },
        { value: "SIDI BOUZEKRI", commune: "" },
        { value: "SIDI CHEIKH|NOUAJI|OULED YOUSSEF", commune: "" },
        { value: "SIDI MJAHED", commune: "" },
        { value: "SIDI SAID", commune: "" },
        { value: "SIDI SLIMANE MOUL AL KIFANE CENTRE", commune: "" },
        { value: "SKHIRAT", commune: "" },
        { value: "SMAALA", commune: "" },
        { value: "TALAGHZA", commune: "" },
        { value: "TAMESNA", commune: "" },
        { value: "TAOURA", commune: "" },
        { value: "TOUARGA", commune: "" },
        { value: "TOULAL", commune: "" },
        { value: "VILLE NOUVELLE", commune: "" },
        { value: "ZAHWA", commune: "" },
        { value: "ZAOUIA SQUELIA AU MUSELÉE MY IDRISS", commune: "" },
        { value: "ZEROUALA", commune: "" },
        { value: "ZITOUNE", commune: "" },
        { value: "ZOUALET", commune: "" }
    ]

});
