Ext.define('App.store.INDH.SousSecteurs', {
    extend: 'Ext.data.Store',

    alias: 'store.soussecteurs',

    fields: ['value', 'secteur'],

    data: [
        { code: 1  , value: "manifestations culturelles", secteur: 8 },
        { code: 2  , value: "Abattoirs", secteur: 16 },
        { code: 3  , value: "Accoucheuses traditionnelles", secteur: 12 },
        { code: 4  , value: "Achat d’équipements, de matériels et outillage", secteur: 13 },
        { code: 5  , value: "Achat de matériel informatique", secteur: 9 },
        { code: 6  , value: "Achat de médicaments", secteur: 12 },
        { code: 7  , value: "Achat de moyens de transport", secteur: 19 },
        { code: 8  , value: "Achat de véhicules utilitaires", secteur: 20 },
        { code: 9  , value: "Aliments pour bétail", secteur: 14 },
        { code: 10 , value: "Ambulances", secteur: 12 },
        { code: 11 , value: "Aménagement des locaux", secteur: 13 },
        { code: 12 , value: "Aménagement des trottoirs", secteur: 0 },
        { code: 13 , value: "Aménagements urbains", secteur: 5 },
        { code: 14 , value: "Animateurs (trices) de formation professionnelle", secteur: 10 },
        { code: 15 , value: "Arboriculture fruitière", secteur: 14 },
        { code: 16 , value: "Artisanat du bois, de la pière et des métaux", secteur: 15 },
        { code: 17 , value: "Arts culinaires", secteur: 16 },
        { code: 18 , value: "Arts vivants et Arts médiatiques", secteur: 8 },
        { code: 19 , value: "Assainissement liqucodee", secteur: 2 },
        { code: 20 , value: "Assainissement solcodee", secteur: 2 },
        { code: 21 , value: "Auberges et maison d’hôte", secteur: 18 },
        { code: 22 , value: "Bacs à ordure", secteur: 2 },
        { code: 23 , value: "Bain- Hammam – Douches", secteur: 16 },
        { code: 24 , value: "Barrages", secteur: 5 },
        { code: 25 , value: "Bibliothèques", secteur: 8 },
        { code: 26 , value: "Bibliothèques scolaires", secteur: 9 },
        { code: 27 , value: "Bicyclettes", secteur: 9 },
        { code: 28 , value: "Bijouterie", secteur: 15 },
        { code: 29 , value: "Blocs sanitaires", secteur: 9 },
        { code: 30 , value: "Bornes Fontaines- Points d'eau", secteur: 1 },
        { code: 31 , value: "Boulangerie-Pâtisserie-", secteur: 16 },
        { code: 32 , value: "Branchement au réseau d'assainissement", secteur: 2 },
        { code: 33 , value: "Branchements électriques", secteur: 4 },
        { code: 34 , value: "Branchements indivcodeuels", secteur: 1 },
        { code: 35 , value: "Camion citerne", secteur: 1 },
        { code: 36 , value: "Camping - écotourisme", secteur: 18 },
        { code: 37 , value: "Cantines scolaires", secteur: 9 },
        { code: 38 , value: "Caravanes médicales", secteur: 12 },
        { code: 39 , value: "Cartes et schémas de précarité", secteur: 22 },
        { code: 40 , value: "Centre - espace ou complexe commercial", secteur: 16 },
        { code: 41 , value: "Centre d’écoute et d’orientation", secteur: 6 },
        { code: 42 , value: "Centre d'accueil des femmes en situation précaire", secteur: 7 },
        { code: 43 , value: "Centre d'accueil pour SDF", secteur: 6 },
        { code: 44 , value: "Centre de formation professionnelle", secteur: 10 },
        { code: 45 , value: "Centre de formation sportive", secteur: 11 },
        { code: 46 , value: "Centre de protection de l'enfance", secteur: 6 },
        { code: 47 , value: "Centre de réinsertion des ex-détenus", secteur: 6 },
        { code: 48 , value: "Centre de santé", secteur: 12 },
        { code: 49 , value: "Centre de soutien scolaire", secteur: 9 },
        { code: 50 , value: "Centre des anciens résistants (combattants)", secteur: 6 },
        { code: 51 , value: "Centre d'hémodialyse", secteur: 12 },
        { code: 52 , value: "Centre Plurcodeisciplinaire", secteur: 7 },
        { code: 53 , value: "Centre polyvalent pour handicapés", secteur: 3 },
        { code: 54 , value: "Centre pour enfants abandonnés", secteur: 6 },
        { code: 55 , value: "Centre pour enfants autistes et souffrant de troubles de la communication", secteur: 3 },
        { code: 56 , value: "Centre pour handicapés moteurs (rééducation fonctionnelle ; Ateliers d’appareillage orthopédique...)", secteur: 3 },
        { code: 57 , value: "Centre pour les aveugles et les malvoyants (Unités d’orthoptie etc ..)", secteur: 3 },
        { code: 58 , value: "Centre pour personnes âgées", secteur: 6 },
        { code: 59 , value: "Centre pour personnes handicapées mentales", secteur: 3 },
        { code: 60 , value: "Centre pour sourds et malentendants", secteur: 3 },
        { code: 61 , value: "Centre pour trisomiques", secteur: 3 },
        { code: 62 , value: "Centre socioculturel et sportif", secteur: 7 },
        { code: 63 , value: "Centre Socioéducatif", secteur: 7 },
        { code: 64 , value: "Centre socio-médical", secteur: 7 },
        { code: 65 , value: "Centre touristique", secteur: 18 },
        { code: 66 , value: "Centres Culturels", secteur: 8 },
        { code: 67 , value: "Circoncision", secteur: 12 },
        { code: 68 , value: "Citernes et Bâches", secteur: 1 },
        { code: 69 , value: "Collecte et Production du lait", secteur: 14 },
        { code: 70 , value: "Collège", secteur: 9 },
        { code: 71 , value: "Commercialisation des poissons", secteur: 17 },
        { code: 72 , value: "Compagne de santé", secteur: 12 },
        { code: 73 , value: "Complexe artisanal", secteur: 15 },
        { code: 74 , value: "Complexe sportif", secteur: 11 },
        { code: 75 , value: "Conférences - Ateliers", secteur: 23 },
        { code: 76 , value: "Cours d’appui", secteur: 9 },
        { code: 77 , value: "Couture et textile", secteur: 15 },
        { code: 78 , value: "Crèche", secteur: 9 },
        { code: 79 , value: "Creusement et Approfondissement des puits", secteur: 1 },
        { code: 80 , value: "Cuir", secteur: 15 },
        { code: 81 , value: "Culte et activités religieuses", secteur: 8 },
        { code: 82 , value: "Culture des légumineuses", secteur: 14 },
        { code: 83 , value: "Cultures maraîchères", secteur: 14 },
        { code: 84 , value: "Dallage des rues", secteur: 0 },
        { code: 85 , value: "Salles, Maisons, Unités ou Modules d\'accouchement des femmes", secteur: 12 },
        { code: 86 , value: "Dar TALIB - Maison de l'étudiant", secteur: 9 },
        { code: 87 , value: "Dar TALIBA - Maison de l'étudiante (Dar Al Fatat)", secteur: 9 },
        { code: 88 , value: "Décharge publique", secteur: 2 },
        { code: 89 , value: "Décoration", secteur: 15 },
        { code: 90 , value: "Dépliants - Brochures- Prospectus", secteur: 21 },
        { code: 91 , value: "Diagnostics Participatifs", secteur: 22 },
        { code: 92 , value: "Digue - Mûr de soutènement", secteur: 5 },
        { code: 93 , value: "Dispensaire", secteur: 12 },
        { code: 94 , value: "Éclairage Public", secteur: 4 },
        { code: 95 , value: "École coranique", secteur: 9 },
        { code: 96 , value: "École primaire", secteur: 9 },
        { code: 97 , value: "Ecole satellite (salle de classe)", secteur: 9 },
        { code: 98 , value: "Ecotourisme", secteur: 18 },
        { code: 99 , value: "Education non formelle", secteur: 9 },
        { code: 100, value: "Électrification Rurale", secteur: 4 },
        { code: 101, value: "Elevage Apicole (Apiculture)", secteur: 14 },
        { code: 102, value: "Elevage Bovins", secteur: 14 },
        { code: 103, value: "Elevage Camelins", secteur: 14 },
        { code: 104, value: "Elevage Caprins", secteur: 14 },
        { code: 105, value: "Elevage Gastéropodes (Héliciculture)", secteur: 14 },
        { code: 106, value: "Elevage lapins(Cuniculture)", secteur: 14 },
        { code: 107, value: "Elevage Ovins", secteur: 14 },
        { code: 108, value: "Elevage Volailles (Aviculture)", secteur: 14 },
        { code: 109, value: "Énergies solaires", secteur: 4 },
        { code: 110, value: "Enquêtes", secteur: 22 },
        { code: 111, value: "Équipements de la pêche", secteur: 17 },
        { code: 112, value: "Equipements de sport", secteur: 11 },
        { code: 113, value: "Espace public", secteur: 5 },
        { code: 114, value: "Espace vert et espace naturel", secteur: 5 },
        { code: 115, value: "Esthétique et Coiffure", secteur: 16 },
        { code: 116, value: "Études de faisabilité des projets", secteur: 22 },
        { code: 117, value: "Examens généraux", secteur: 12 },
        { code: 118, value: "Exploitation Agricole", secteur: 14 },
        { code: 119, value: "Extension du réseau d'AEP", secteur: 1 },
        { code: 120, value: "Filières  de service", secteur: 16 },
        { code: 121, value: "Films - Documents - CD ROM", secteur: 21 },
        { code: 122, value: "Fonctionnement -Réparation des véhicules", secteur: 19 },
        { code: 123, value: "Forêt", secteur: 5 },
        { code: 124, value: "Formation des associations", secteur: 23 },
        { code: 125, value: "Formation des CLDH-CPDH-CRDH", secteur: 23 },
        { code: 126, value: "Formation des EAC/Q", secteur: 23 },
        { code: 127, value: "Formation des élus", secteur: 23 },
        { code: 128, value: "Formation des porteurs de projets", secteur: 23 },
        { code: 129, value: "Formation des représentants des services extérieurs", secteur: 23 },
        { code: 130, value: "Formation en informatique", secteur: 9 },
        { code: 131, value: "Fosses septiques et puits perdus", secteur: 2 },
        { code: 132, value: "Fournitures scolaires", secteur: 9 },
        { code: 133, value: "Foyer Féminin", secteur: 7 },
        { code: 134, value: "Frais divers de fonctionnement", secteur: 20 },
        { code: 135, value: "Garderie des enfants", secteur: 9 },
        { code: 136, value: "Gites touristiques", secteur: 18 },
        { code: 137, value: "Groupe électrogène", secteur: 4 },
        { code: 138, value: "Hôpital (aménagement et équipement)", secteur: 12 },
        { code: 139, value: "Hôtellerie", secteur: 18 },
        { code: 140, value: "Hôtellerie et Restauration", secteur: 16 },
        { code: 141, value: "Indemnités EAC/EAQ", secteur: 20 },
        { code: 142, value: "Industrie agro-alimentaire", secteur: 16 },
        { code: 143, value: "Industrie du bois", secteur: 16 },
        { code: 144, value: "Internats - Réscodeence de l'élève", secteur: 9 },
        { code: 145, value: "Irrigation goutte-à-goutte", secteur: 14 },
        { code: 146, value: "Irrigation gravitaire - Seguias", secteur: 14 },
        { code: 147, value: "Irrigation par aspersion", secteur: 14 },
        { code: 148, value: "Journaux, presses", secteur: 21 },
        { code: 149, value: "Logement de fonction", secteur: 12 },
        { code: 150, value: "Logement d'Instituteur (trice)", secteur: 9 },
        { code: 151, value: "Lotissement", secteur: 5 },
        { code: 152, value: "Lunettes", secteur: 12 },
        { code: 153, value: "Lycée", secteur: 9 },
        { code: 154, value: "Machines agricoles", secteur: 14 },
        { code: 155, value: "Maison de bienfaisance", secteur: 6 },
        { code: 156, value: "Maison des jeunes", secteur: 11 },
        { code: 157, value: "Maison du Citoyen - Maison du Quartier", secteur: 7 },
        { code: 158, value: "Manifestations sportives", secteur: 11 },
        { code: 159, value: "Matériaux de construction", secteur: 5 },
        { code: 160, value: "Matériel de santé- Appareils de santé", secteur: 12 },
        { code: 161, value: "Matériels et mobiliers de bureau", secteur: 20 },
        { code: 162, value: "Menuiserie", secteur: 16 },
        { code: 163, value: "Métallurgie", secteur: 15 },
        { code: 164, value: "Minibus et autocar de transport scolaire", secteur: 9 },
        { code: 165, value: "Mosquée / Cimetière", secteur: 8 },
        { code: 166, value: "Moulins de Céréales", secteur: 14 },
        { code: 167, value: "Mûrs de clôture", secteur: 9 },
        { code: 168, value: "Opération cataracte", secteur: 12 },
        { code: 169, value: "Organisation des marchands ambulants-Organisation des métiers", secteur: 16 },
        { code: 170, value: "Ouvrages d’art ou de franchissement", secteur: 0 },
        { code: 171, value: "Panneaux signalétiques", secteur: 21 },
        { code: 172, value: "Pêche maritime artisanale ou côtière", secteur: 17 },
        { code: 173, value: "Pêche maritime et fluviale", secteur: 17 },
        { code: 174, value: "Pépinière – Plantations", secteur: 14 },
        { code: 175, value: "Pisciculture", secteur: 17 },
        { code: 176, value: "Piscine", secteur: 11 },
        { code: 177, value: "Pistes", secteur: 0 },
        { code: 178, value: "Plantes aromatiques et médicinales", secteur: 14 },
        { code: 179, value: "Plasturgie", secteur: 15 },
        { code: 180, value: "Poterie-Céramique", secteur: 15 },
        { code: 181, value: "Préscolaire", secteur: 9 },
        { code: 182, value: "Protection contre l’érosion et les inondations", secteur: 5 },
        { code: 183, value: "Protection de l'Environnement", secteur: 5 },
        { code: 184, value: "Reboisement", secteur: 5 },
        { code: 185, value: "Réhabilitation - extension du réseau", secteur: 2 },
        { code: 186, value: "Réhabilitation des canalisations", secteur: 1 },
        { code: 187, value: "Rencontres, Séminaires, Manifestations …", secteur: 21 },
        { code: 188, value: "Reportage - Audiovisuel", secteur: 21 },
        { code: 189, value: "Réservoirs et Châteaux", secteur: 1 },
        { code: 190, value: "Restructuration de l’habitat insalubre", secteur: 5 },
        { code: 191, value: "Routes", secteur: 0 },
        { code: 192, value: "Salle de sport (salle couverte, salle omnisport..etc.)", secteur: 11 },
        { code: 193, value: "Salle multimédia", secteur: 9 },
        { code: 194, value: "Salles de lecture", secteur: 8 },
        { code: 195, value: "Salles informatiques et multimédia", secteur: 16 },
        { code: 196, value: "Salles intégrées pour enfants handicapés", secteur: 3 },
        { code: 197, value: "Scierie", secteur: 16 },
        { code: 198, value: "Sculpture-Peinture- Musique -Poésie-Architecture", secteur: 8 },
        { code: 199, value: "Séminaires et journées d’études", secteur: 23 },
        { code: 200, value: "Sensibilisation à la protection de l'environnement", secteur: 5 },
        { code: 201, value: "Sessions Ateliers de formation ou de Qualification Professionnelle", secteur: 10 },
        { code: 202, value: "Scodeérurgie", secteur: 15 },
        { code: 203, value: "Sites Web", secteur: 21 },
        { code: 204, value: "Sources - METFIA KHOUTARA", secteur: 1 },
        { code: 205, value: "Station de pompage", secteur: 1 },
        { code: 206, value: "Station de traitement", secteur: 1 },
        { code: 207, value: "Station d'épuration", secteur: 2 },
        { code: 208, value: "Subvention pour le fonctionnement des centres", secteur: 13 },
        { code: 209, value: "Tapisserie", secteur: 15 },
        { code: 210, value: "Télécommunication", secteur: 9 },
        { code: 211, value: "Terrain de sport - Espace de sport", secteur: 11 },
        { code: 212, value: "Tracteur", secteur: 14 },
        { code: 213, value: "Traitement des déchets", secteur: 2 },
        { code: 214, value: "Transformation des légumes et fruits", secteur: 16 },
        { code: 215, value: "Transformation laitière - Fromagerie", secteur: 14 },
        { code: 216, value: "Transport de marchandises", secteur: 19 },
        { code: 217, value: "Transport des déchets ménagers", secteur: 2 },
        { code: 218, value: "Triporteurs", secteur: 19 },
        { code: 219, value: "Unité de trituration d'olives", secteur: 14 },
        { code: 220, value: "Unité mobile et UMAS", secteur: 12 },
        { code: 221, value: "Université", secteur: 9 },
        { code: 222, value: "Urbanisme", secteur: 5 },
        { code: 223, value: "Valorisation du cactus", secteur: 14 },
        { code: 224, value: "Valorsation de l'argnier", secteur: 14 },
        { code: 225, value: "Velomoteurs", secteur: 19 }
    ]

});
